service: 
  name: swagger-doc-testing
provider:
  name: aws
  runtime: java8
  region: us-east-2
  versionFunctions: false
  memorySize: 1024
  timeout: 30  
plugins:
    - serverless-aws-documentation
custom:
  documentation:
    info:
      version: "2"
      title: "Name of your API"
      description: Some example API
package:
  artifact: build/distributions/serverless-swagger-1.0.zip
functions:
  swagger:
    handler: com.serverless.handler.RestApiHandler
    events:
      - http:
          path: swagger
          method: get
          integration: lambda
          cors: true
          documentation:
            summary: "Create something"
            tags:
            - "Data Creation"
            - "Some other tag"
            requestBody:
              description: "Request body description"

  spec:
    handler: com.serverless.handler.SpecHandler
    events:
      - http:
          path: /swagger/spec
          description: Gets swagger json
          method: get
          integration: lambda
          cors: true
          documentation:
            summary: "Create something"
            tags:
            - "Data Creation"
            - "Some other tag"
            requestBody:
              description: "Request body description"

          